version: "3.9"

services:
  mysqldb:
    image: midna3/vedu-db:1.3
    ports:
      - "3306:3306"
    networks:
      - api-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: educacao
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: springuser
      MYSQL_PASSWORD: spring
      MYSQL_ROOT_HOST: '%'
    healthcheck:
      test: 'mysql -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e "USE $$MYSQL_DATABASE;"'
      interval: 30s
      timeout: 30s
      retries: 10

  api:
    image: midna3/vgestor-api:latest
    ports:
      - "8080:8080"
    networks:
      - api-mysql
    depends_on:
      mysqldb:
        condition: service_healthy

networks:
  api-mysql: 
